name: Output event details on issues
on: issues
jobs:
  output_details:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue detail
        run: |
          echo "An action on Issues was performed."
          echo "Event name: ${{ toJSON(github.event) }}"
