name: Workflow 1
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v4
      - name: Run linter
        run: npm run lint
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: npm run test
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: run deploy
        run: npm run build
  